### ISSUE TITLE
is not safe to call RunOptimize() on some ReadFrom inputs  

### ISSUE THREAD

**Issue by fzerorubigd** [RoaringBitmap/roaring#181]
Assuming any data is valid if loaded by ReadFrom , calling RunOptimize() should be safe. but for example in this case : 

```go
package main

import (
	"encoding/base64"
	"log"

	"github.com/RoaringBitmap/roaring"
)

func main() {
	// some invalid data, base64 for readability of non-visual chars
	t, _ := base64.StdEncoding.DecodeString("OzAEAAAwMAAAMDABADAwAAAwMAEAMDAAADAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDA=")

	m := roaring.NewBitmap()

	// no error on invalid data
	err := m.UnmarshalBinary(t)
	if err != nil {
		log.Fatal(err)
	}
	m.RunOptimize()
}
``` 
Result is : 
```
panic: then fundamental arrayContainer assumption of deduplicated content was broken

goroutine 1 [running]:
github.com/RoaringBitmap/roaring.(*arrayContainer).numberOfRuns(0xc42000a120, 0x1)
	/home/f0rud/src/github.com/RoaringBitmap/roaring/arraycontainer.go:927 +0xca
github.com/RoaringBitmap/roaring.(*arrayContainer).toEfficientContainer(0xc42000a120, 0x533fa0, 0xc42000a100)
	/home/f0rud/src/github.com/RoaringBitmap/roaring/arraycontainer.go:942 +0x2f
github.com/RoaringBitmap/roaring.(*roaringArray).runOptimize(0xc420049f10)
	/home/f0rud/src/github.com/RoaringBitmap/roaring/roaringarray.go:130 +0x7a
github.com/RoaringBitmap/roaring.(*Bitmap).RunOptimize(0xc420049f10)
	/home/f0rud/src/github.com/RoaringBitmap/roaring/roaring.go:96 +0x2d
main.main()
	/home/f0rud/src/roar/main.go:21 +0xfd
exit status 2

```
also there was another panic (" panic: then fundamental arrayContainer assumption of sorted ac.content was broken ") for this payload (base64 of payload): 
```
OzAFAAAwMAAAMDABADAwAAAwMAEAMDAAADAwAAAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMP8wMDAwMAAwMDAw
```

either 
- My assumption is wrong 
- or ReadFrom should validate input for "fundamental arrayContainer assumptions"

**Comment by maciej** [comment]
That's correct. There are adversarial inputs that will be accepted by either `ReadFrom` or `FromBuffer` without warning and however will result in errors / panics when operating on them. However I don't think that we should harden `ReadFrom`/`FromBuffer` against every such input at the expense of performance. If there is a valid use case when potentially adversarial input is received from an untrusted party we should use other mechanisms for validating it. `*Bitmap.SafeReadFrom` perhaps or `roaring.VerifyUntrustedBuffer`.

**Comment by jacksonrnewhouse** [comment]
I believe this happens because ReadFrom does not actually inspect the contents of the containers at all, instead just passing references to the slices that represent the contents. This allows initialization to be O(containers), rather than O(cardinality), and I'd imagine we couldn't validate the contents without a significant overhead.

**Comment by Oppen** [comment]
A `Validate` function would be best. If the user trusts the input (they generated it, for example) they can avoid paying the price, but if something comes down the wire the sensible programmer can discard invalid input.

**Comment by lemire** [comment]
@Oppen It is a nice idea, yes. A validate function might also be able to return (for free) some other information.
