### ISSUE TITLE
Crash in Maximum with empty bitmap

### ISSUE THREAD

**Issue by comunidadio** [RoaringBitmap/roaring#336]
Minimal testcase below:

```
testcase $ go mod init example.org/testcase && go mod tidy
go: creating new go.mod: module example.org/testcase
go: to add module requirements and sums:
	go mod tidy
go: finding module for package github.com/RoaringBitmap/roaring
go: found github.com/RoaringBitmap/roaring in github.com/RoaringBitmap/roaring v0.9.4
testcase $ cat roaringmax.go 
package main

import "github.com/RoaringBitmap/roaring"

func main() {
	rb := roaring.New()
	rb.Maximum()
}
testcase $ go run roaringmax.go 
panic: runtime error: index out of range [-1]

goroutine 1 [running]:
github.com/RoaringBitmap/roaring.(*Bitmap).Maximum(0xc000060000)
	/Users/c/dev/go/pkg/mod/github.com/!roaring!bitmap/roaring@v0.9.4/roaring.go:475 +0x94
main.main()
	/Users/c/dev/tmp/testcase/roaringmax.go:7 +0x3d
exit status 2
```

**Comment by lemire** [comment]
The maximum of an empty set is undefined. I will add an explicit panic.

**Comment by lemire** [comment]
Note that the functions are documented as assuming that the set is not empty. I have revised the code to add an explicit panic.
