### ISSUE TITLE
smat tests for run containers

### ISSUE THREAD

**Issue by glycerine** [RoaringBitmap/roaring#79]
turning checkbox into issue, from #70:
update the unit tests to aggressively call runOptimize alot, and run the smat tests.

**Comment by glycerine** [comment]
On my `rle_testing` branch, I sprinkled runOptmize through the top level operations, then ran smat. 

After 26 minutes smat did find one hang/timeout, output here:

~~~
program hanged (timeout 200 seconds)

SIGABRT: abort
PC=0x52cdb m=0

goroutine 0 [idle]:
runtime.mach_semaphore_wait(0x803, 0x2a501, 0x209b60, 0x360e0, 0xc42001adc8, 0x209b60, 0x7fff5fbff280, 0x498f3, 0xffffffffffffffff, 0x0, ...)
	/var/folders/6s/zdc0hvvx7kqcglg5yqm3kl4r0000gn/T/go-fuzz-build161702396/goroot/src/runtime/sys_darwin_amd64.s:418 +0xb
runtime.semasleep1(0xffffffffffffffff, 0x0)
	/var/folders/6s/zdc0hvvx7kqcglg5yqm3kl4r0000gn/T/go-fuzz-build161702396/goroot/src/runtime/os_darwin.go:435 +0x4b
runtime.semasleep.func1()
	/var/folders/6s/zdc0hvvx7kqcglg5yqm3kl4r0000gn/T/go-fuzz-build161702396/goroot/src/runtime/os_darwin.go:451 +0x33
runtime.systemstack(0x7fff5fbff2a8)
	/var/folders/6s/zdc0hvvx7kqcglg5yqm3kl4r0000gn/T/go-fuzz-build161702396/goroot/src/runtime/asm_amd64.s:314 +0xab
runtime.semasleep(0xffffffffffffffff, 0x0)
	/var/folders/6s/zdc0hvvx7kqcglg5yqm3kl4r0000gn/T/go-fuzz-build161702396/goroot/src/runtime/os_darwin.go:452 +0x44
runtime.notesleep(0x209fd0)
	/var/folders/6s/zdc0hvvx7kqcglg5yqm3kl4r0000gn/T/go-fuzz-build161702396/goroot/src/runtime/lock_sema.go:166 +0x9f
runtime.stopm()
	/var/folders/6s/zdc0hvvx7kqcglg5yqm3kl4r0000gn/T/go-fuzz-build161702396/goroot/src/runtime/proc.go:1594 +0xad
runtime.exitsyscall0(0xc4200001a0)
	/var/folders/6s/zdc0hvvx7kqcglg5yqm3kl4r0000gn/T/go-fuzz-build161702396/goroot/src/runtime/proc.go:2638 +0x128
runtime.mcall(0x7fff5fbff3b0)
	/var/folders/6s/zdc0hvvx7kqcglg5yqm3kl4r0000gn/T/go-fuzz-build161702396/goroot/src/runtime/asm_amd64.s:240 +0x5b

goroutine 1 [runnable]:
github.com/RoaringBitmap/roaring.(*roaringArray).resize(0xc4200eb110, 0xedd1)
	/var/folders/6s/zdc0hvvx7kqcglg5yqm3kl4r0000gn/T/go-fuzz-build161702396/gopath/src/github.com/RoaringBitmap/roaring/roaringarray.go:192
github.com/RoaringBitmap/roaring.(*roaringArray).removeAtIndex(0xc4200eb110, 0x0)
	/var/folders/6s/zdc0hvvx7kqcglg5yqm3kl4r0000gn/T/go-fuzz-build161702396/gopath/src/github.com/RoaringBitmap/roaring/roaringarray.go:310 +0x1c1
github.com/RoaringBitmap/roaring.(*Bitmap).Flip(0xc4200eb110, 0xffffffff, 0x100000000)
	/var/folders/6s/zdc0hvvx7kqcglg5yqm3kl4r0000gn/T/go-fuzz-build161702396/gopath/src/github.com/RoaringBitmap/roaring/roaring.go:983 +0x42e
github.com/RoaringBitmap/roaring.smatFlip.func1(0xc4200d1c30)
	/var/folders/6s/zdc0hvvx7kqcglg5yqm3kl4r0000gn/T/go-fuzz-build161702396/gopath/src/github.com/RoaringBitmap/roaring/smat.go:331 +0x66
github.com/RoaringBitmap/roaring.(*smatContext).withPair(0xc4200fa420, 0x0, 0xc4201fcc68)
	/var/folders/6s/zdc0hvvx7kqcglg5yqm3kl4r0000gn/T/go-fuzz-build161702396/gopath/src/github.com/RoaringBitmap/roaring/smat.go:188 +0xd8
github.com/RoaringBitmap/roaring.smatFlip(0xc4200fa420)
	/var/folders/6s/zdc0hvvx7kqcglg5yqm3kl4r0000gn/T/go-fuzz-build161702396/gopath/src/github.com/RoaringBitmap/roaring/smat.go:334 +0x67
github.com/RoaringBitmap/roaring.smatWrap.func1(0x13c060, 0xc4200fa420, 0x15c026, 0x3, 0xc42003dce0)
	/var/folders/6s/zdc0hvvx7kqcglg5yqm3kl4r0000gn/T/go-fuzz-build161702396/gopath/src/github.com/RoaringBitmap/roaring/smat.go:176 +0x5c
github.com/RoaringBitmap/roaring.smatAction.func1(0x13c060, 0xc4200fa420, 0x14, 0xc42003ddb0, 0x1)
	/var/folders/6s/zdc0hvvx7kqcglg5yqm3kl4r0000gn/T/go-fuzz-build161702396/gopath/src/github.com/RoaringBitmap/roaring/smat.go:168 +0x12a
github.com/mschoch/smat.runReader(0x13c060, 0xc4200fa420, 0x53, 0x54, 0xc4200142a0, 0x1f41c0, 0xc4200fa450, 0x0, 0x0, 0x0)
	/var/folders/6s/zdc0hvvx7kqcglg5yqm3kl4r0000gn/T/go-fuzz-build161702396/gopath/src/github.com/mschoch/smat/smat.go:136 +0x4d8
github.com/mschoch/smat.Fuzz(0x13c060, 0xc4200fa420, 0x53, 0x54, 0xc4200142a0, 0x2cc000, 0xc, 0x200000, 0x58536134)
	/var/folders/6s/zdc0hvvx7kqcglg5yqm3kl4r0000gn/T/go-fuzz-build161702396/gopath/src/github.com/mschoch/smat/smat.go:78 +0x102
github.com/RoaringBitmap/roaring.Fuzz(0x2cc000, 0xc, 0x200000, 0x3)
	/var/folders/6s/zdc0hvvx7kqcglg5yqm3kl4r0000gn/T/go-fuzz-build161702396/gopath/src/github.com/RoaringBitmap/roaring/smat.go:73 +0xc5
go-fuzz-dep.Main(0x16a9b0)
	/var/folders/6s/zdc0hvvx7kqcglg5yqm3kl4r0000gn/T/go-fuzz-build161702396/goroot/src/go-fuzz-dep/main.go:49 +0xe8
main.main()
	/var/folders/6s/zdc0hvvx7kqcglg5yqm3kl4r0000gn/T/go-fuzz-build161702396/gopath/src/github.com/RoaringBitmap/roaring/go.fuzz.main/main.go:10 +0x2d

rax    0xe
rbx    0x209ec0
rcx    0x7fff5fbff220
rdx    0x7fff5fbff2a8
rdi    0x803
rsi    0x1
rbp    0x7fff5fbff258
rsp    0x7fff5fbff220
r8     0xc4200001a0
r9     0x11
r10    0xffffffee
r11    0x286
r12    0x40
r13    0x4c0
r14    0x14
r15    0x1fffffffffffff
rip    0x52cdb
rflags 0x286
cs     0x7
fs     0x0
gs     0x0
exit status 2
~~~

**Comment by glycerine** [comment]
the open question is where the calls to

rb.highlowcontainer.runOptimize()

should go in the unit tests. I could use some assistance with placing them.

**Comment by glycerine** [comment]
let it run for over an hour, the above timeout was the only thing detected.
~~~
....
2016/12/15 22:55:55 slaves: 4, corpus: 10 (1h14m ago), crashers: 1, restarts: 1/397, execs: 25449 (5\
/sec), cover: 516, uptime: 1h20m
2016/12/15 22:55:58 slaves: 4, corpus: 10 (1h14m ago), crashers: 1, restarts: 1/397, execs: 25449 (5/sec), cover: 516, uptime: 1h20m
2016/12/15 22:56:01 slaves: 4, corpus: 10 (1h14m ago), crashers: 1, restarts: 1/397, execs: 25449 (5\
/sec), cover: 516, uptime: 1h20m
2016/12/15 22:56:04 slaves: 4, corpus: 10 (1h14m ago), crashers: 1, restarts: 1/397, execs: 25449 (5/sec), cover: 516, uptime: 1h20m
  C-c C-c2016/12/15 22:56:05 shutting down...
~~~

**Comment by lemire** [comment]
@glycerine  I think we do have a run containers in smat tests now. What is the status of this issue?

**Comment by glycerine** [comment]
ok with me to close it!
